import { Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { AuthProvider, useAuth } from './AuthProvider'
import { BrandingProvider } from './BrandingProvider'
import { WorkspaceLayout } from '../layouts/WorkspaceLayout'
import { AdminDashboard, OperatorDashboard, StudentDashboard, TeacherDashboard } from '../pages/Dashboards'
import { BrandingPage, CertificateVerify, ExamWorkspace, LiveClassPage, LoginPage } from '../pages/FeaturePages'
import { SetupWizard } from '../pages/SetupWizard'
import { ConnectedResourcePage as ResourcePage } from '../pages/ConnectedResourcePage'
import type { Role } from '../types'
function Guard({role}:{role:Role}){const {user,loading}=useAuth();const location=useLocation();if(loading)return <div className="loading-page"><span/><p>Loading your workspace…</p></div>;if(!user)return <Navigate to="/login" state={{from:location}} replace/>;const normalized=user.roles.map(v=>v.toLowerCase());if(!normalized.includes(role)&&!(role==='administrator'&&normalized.includes('admin')))return <Navigate to={`/${normalized[0]??'student'}`} replace/>;return <WorkspaceLayout role={role}/>}
const adminPages:Record<string,string>={units:'Units',courses:'Courses',levels:'Levels',modules:'Modules',classes:'Classes',enrollments:'Enrollments',users:'Users',administrators:'Administrators',teachers:'Teachers',students:'Students',operators:'Operators','academic-policy':'Academic policy',billing:'Billing',support:'Support',certificates:'Certificates',audit:'Audit',settings:'Settings'}
const teacherPages:Record<string,string>={classes:'My classes',lessons:'Lessons',exercises:'Exercises','grading/exercises':'Exercise grading',exams:'Exams','grading/exams':'Exam grading',attendance:'Attendance',students:'Students',support:'Support'}
const studentPages:Record<string,string>={classes:'My classes',lessons:'Lessons',exercises:'Exercises',exams:'Exams',grades:'Grades',performance:'Performance',attendance:'Attendance',support:'Support',billing:'Billing',certificate:'Certificate'}
const operatorPages:Record<string,string>={students:'Students',enrollments:'Enrollments',billing:'Billing',notifications:'Notifications',support:'Support',profile:'Profile'}
function resourceKind(path:string){const last=path.split('/').filter(Boolean).at(-1)??path;if(path.includes('grading'))return path.includes('exam')?'exams':'exercises';return last}
export function App(){return <BrandingProvider><AuthProvider><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/setup" element={<SetupWizard/>}/><Route path="/certificate/verify" element={<CertificateVerify/>}/><Route path="/admin" element={<Guard role="administrator"/>}><Route index element={<AdminDashboard/>}/><Route path="branding" element={<BrandingPage/>}/>{Object.entries(adminPages).map(([path,title])=><Route path={`${path}/*`} key={path} element={<ResourcePage kind={resourceKind(path)} title={title}/>}/>)}</Route><Route path="/teacher" element={<Guard role="teacher"/>}><Route index element={<TeacherDashboard/>}/><Route path="live/:lessonId" element={<LiveClassPage/>}/><Route path="exams/:id/attempt" element={<ExamWorkspace/>}/>{Object.entries(teacherPages).map(([path,title])=><Route path={`${path}/*`} key={path} element={<ResourcePage kind={resourceKind(path)} title={title}/>}/>)}</Route><Route path="/student" element={<Guard role="student"/>}><Route index element={<StudentDashboard/>}/><Route path="live/:lessonId" element={<LiveClassPage/>}/><Route path="exams/:id" element={<ExamWorkspace/>}/>{Object.entries(studentPages).map(([path,title])=><Route path={`${path}/*`} key={path} element={<ResourcePage kind={resourceKind(path)} title={title}/>}/>)}</Route><Route path="/operator" element={<Guard role="operator"/>}><Route index element={<OperatorDashboard/>}/>{Object.entries(operatorPages).map(([path,title])=><Route path={`${path}/*`} key={path} element={<ResourcePage kind={resourceKind(path)} title={title}/>}/>)}</Route><Route path="*" element={<Navigate to="/login" replace/>}/></Routes></AuthProvider></BrandingProvider>}
