CREATE TABLE academic_policies (school_id uuid PRIMARY KEY REFERENCES schools(id), minimum_passing_score_scaled integer NOT NULL, exercise_weight_basis_points integer NOT NULL, exam_weight_basis_points integer NOT NULL, minimum_attendance_basis_points integer NOT NULL, require_all_mandatory_exams boolean NOT NULL DEFAULT true, require_all_mandatory_exercises boolean NOT NULL DEFAULT true, updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid NOT NULL REFERENCES users(id), CHECK(exercise_weight_basis_points+exam_weight_basis_points=10000), CHECK(minimum_attendance_basis_points BETWEEN 0 AND 10000));
CREATE TABLE academic_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id uuid NOT NULL UNIQUE REFERENCES enrollments(id), exercise_average_scaled integer NOT NULL DEFAULT 0, exam_average_scaled integer NOT NULL DEFAULT 0, attendance_basis_points integer NOT NULL DEFAULT 0, final_score_scaled integer NOT NULL DEFAULT 0, result text NOT NULL CHECK(result IN ('in_progress','pending_review','approved','failed')), calculated_at timestamptz NOT NULL DEFAULT now(), closed_by uuid REFERENCES users(id), closed_at timestamptz);
CREATE TABLE academic_overrides (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), academic_result_id uuid NOT NULL REFERENCES academic_results(id), previous_result text NOT NULL, new_result text NOT NULL, reason text NOT NULL CHECK(length(reason)>=5), approved_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE billing_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), student_id uuid NOT NULL REFERENCES users(id), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,student_id));
CREATE TABLE invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), student_id uuid NOT NULL REFERENCES users(id), enrollment_id uuid REFERENCES enrollments(id), description text NOT NULL, amount_cents bigint NOT NULL CHECK(amount_cents>0), due_date date NOT NULL, status text NOT NULL CHECK(status IN ('draft','issued','paid','overdue','cancelled')), provider text NOT NULL, provider_reference text, boleto_url text, boleto_barcode text, pix_data text, issued_at timestamptz, paid_at timestamptz, cancelled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX invoices_student_status_idx ON invoices(school_id,student_id,status);
CREATE INDEX invoices_due_idx ON invoices(school_id,due_date,status);
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid NOT NULL REFERENCES invoices(id), amount_cents bigint NOT NULL CHECK(amount_cents>0), provider_reference text, paid_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE notification_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), type text NOT NULL, channel text NOT NULL CHECK(channel IN ('in_app','email_future')), title_template text NOT NULL, message_template text NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE(school_id,type,channel));
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), user_id uuid NOT NULL REFERENCES users(id), type text NOT NULL, title text NOT NULL, message text NOT NULL, resource_type text, resource_id uuid, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX notifications_user_idx ON notifications(user_id,read_at,created_at DESC);

CREATE SEQUENCE support_ticket_number_seq;
CREATE TABLE support_tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), ticket_number bigint NOT NULL DEFAULT nextval('support_ticket_number_seq'), requester_user_id uuid NOT NULL REFERENCES users(id), opened_by_user_id uuid NOT NULL REFERENCES users(id), category text NOT NULL CHECK(category IN ('technical','academic','financial','access','classroom','billing','other')), subject text NOT NULL, description text NOT NULL, priority text NOT NULL CHECK(priority IN ('low','normal','high','urgent')), status text NOT NULL CHECK(status IN ('open','assigned','in_progress','waiting_user','resolved','closed')), assigned_to_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, closed_at timestamptz, UNIQUE(school_id,ticket_number));
CREATE INDEX support_tickets_queue_idx ON support_tickets(school_id,status,assigned_to_user_id,updated_at);
CREATE TABLE support_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id), author_user_id uuid NOT NULL REFERENCES users(id), message text NOT NULL, internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE support_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id), assigned_to uuid NOT NULL REFERENCES users(id), assigned_by uuid NOT NULL REFERENCES users(id), assigned_at timestamptz NOT NULL DEFAULT now(), unassigned_at timestamptz);
CREATE TABLE support_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id), message_id uuid REFERENCES support_messages(id), storage_key text NOT NULL, client_file_name text NOT NULL, mime_type text NOT NULL CHECK(mime_type IN ('image/png','image/jpeg','image/webp','application/pdf','text/plain')), size bigint NOT NULL CHECK(size>=0), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE certificates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), enrollment_id uuid NOT NULL UNIQUE REFERENCES enrollments(id), student_id uuid NOT NULL REFERENCES users(id), course_id uuid NOT NULL REFERENCES courses(id), level_id uuid REFERENCES course_levels(id), certificate_number text NOT NULL, verification_code text NOT NULL, issued_at timestamptz NOT NULL, completion_date date NOT NULL, workload_hours integer NOT NULL CHECK(workload_hours>=0), final_score_scaled integer, storage_key text NOT NULL, revoked_at timestamptz, revoked_by uuid REFERENCES users(id), revocation_reason text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,certificate_number), UNIQUE(verification_code));
CREATE UNIQUE INDEX certificates_verification_idx ON certificates(verification_code);
ALTER TABLE enrollments ADD CONSTRAINT enrollments_certificate_fk FOREIGN KEY(certificate_id) REFERENCES certificates(id);

CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), user_id uuid REFERENCES users(id), action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb NOT NULL DEFAULT '{}', ip_address inet, user_agent text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_events_school_created_idx ON audit_events(school_id,created_at DESC);

CREATE TABLE setup_progress (id boolean PRIMARY KEY DEFAULT true CHECK(id), current_step text NOT NULL DEFAULT 'welcome', completed_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());

COMMENT ON COLUMN invoices.amount_cents IS 'Money is stored as integer minor currency units.';
COMMENT ON COLUMN academic_results.final_score_scaled IS 'Scores use scale 100: 8.50 is stored as 850.';
COMMENT ON COLUMN academic_policies.exercise_weight_basis_points IS 'Weights use basis points and must total 10000.';
