import { useState } from 'react'
import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { Bell, BookOpen, Building2, CalendarDays, ChevronDown, ClipboardCheck, FileBadge, GraduationCap, Headphones, LayoutDashboard, Menu, Receipt, Search, Settings, ShieldCheck, TicketCheck, Users, X } from 'lucide-react'
import { useBranding } from '../app/BrandingProvider'
import { useAuth } from '../app/AuthProvider'
import { SearchBox } from '../components/ui'
import type { Role } from '../types'
type NavItem = { label: string; path: string; icon: typeof LayoutDashboard }
const navigation: Record<Role, NavItem[]> = {
  administrator: [ ['Dashboard','/admin',LayoutDashboard],['Units','/admin/units',Building2],['Courses','/admin/courses',BookOpen],['Classes','/admin/classes',CalendarDays],['Enrollments','/admin/enrollments',GraduationCap],['Users','/admin/users',Users],['Teachers','/admin/teachers',Users],['Students','/admin/students',Users],['Operators','/admin/operators',Headphones],['Academic Policy','/admin/academic-policy',ClipboardCheck],['Billing','/admin/billing',Receipt],['Support','/admin/support',TicketCheck],['Certificates','/admin/certificates',FileBadge],['Branding','/admin/branding',Settings],['Audit','/admin/audit',ShieldCheck],['Settings','/admin/settings',Settings] ].map(([label,path,icon])=>({label:label as string,path:path as string,icon:icon as typeof LayoutDashboard})),
  teacher: [ ['My Day','/teacher',LayoutDashboard],['Classes','/teacher/classes',BookOpen],['Lessons','/teacher/lessons',CalendarDays],['Exercises','/teacher/exercises',ClipboardCheck],['Exercise Grading','/teacher/grading/exercises',ClipboardCheck],['Exams','/teacher/exams',FileBadge],['Exam Grading','/teacher/grading/exams',FileBadge],['Attendance','/teacher/attendance',Users],['Students','/teacher/students',GraduationCap],['Support','/teacher/support',TicketCheck] ].map(([label,path,icon])=>({label:label as string,path:path as string,icon:icon as typeof LayoutDashboard})),
  student: [ ['Home','/student',LayoutDashboard],['Classes','/student/classes',BookOpen],['Lessons','/student/lessons',CalendarDays],['Exercises','/student/exercises',ClipboardCheck],['Exams','/student/exams',FileBadge],['Grades','/student/grades',GraduationCap],['Performance','/student/performance',LayoutDashboard],['Attendance','/student/attendance',Users],['Billing','/student/billing',Receipt],['Support','/student/support',TicketCheck],['Certificate','/student/certificate',FileBadge] ].map(([label,path,icon])=>({label:label as string,path:path as string,icon:icon as typeof LayoutDashboard})),
  operator: [ ['Dashboard','/operator',LayoutDashboard],['Students','/operator/students',Users],['Enrollments','/operator/enrollments',GraduationCap],['Billing','/operator/billing',Receipt],['Notifications','/operator/notifications',Bell],['Support','/operator/support',TicketCheck],['Profile','/operator/profile',Settings] ].map(([label,path,icon])=>({label:label as string,path:path as string,icon:icon as typeof LayoutDashboard}))
}
export function WorkspaceLayout({ role }: { role: Role }) { const [open,setOpen]=useState(false); const { schoolDisplayName, systemTitle }=useBranding(); const { user, logout }=useAuth(); const location=useLocation(); return <div className="workspace"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark"><GraduationCap/></div><div><b>{schoolDisplayName}</b><span>{systemTitle}</span></div><button aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label={`${role} navigation`}>{navigation[role].map(item=><NavLink key={item.path} to={item.path} end={item.path===`/${role==='administrator'?'admin':role}`} onClick={()=>setOpen(false)}><item.icon/><span>{item.label}</span></NavLink>)}</nav><div className="sidebar-footer"><div className="avatar">{user?.name.slice(0,2).toUpperCase() ?? 'FH'}</div><div><b>{user?.name ?? 'FluentHub User'}</b><span>{role}</span></div><button aria-label="Account menu" onClick={()=>void logout()}><ChevronDown/></button></div></aside><main><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><SearchBox placeholder={`Search ${role} workspace`}/><div className="top-actions"><button aria-label="Global search"><Search/></button><button aria-label="Notifications" className="notification"><Bell/><span/></button><div className="avatar">{user?.name.slice(0,2).toUpperCase() ?? 'FH'}</div></div></header><div className="content" key={location.pathname}><Outlet/></div></main>{open&&<button className="backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</div> }
