import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { Filter, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { Badge, EmptyState, PageHeader } from '../components/ui'

type Row = Record<string, unknown>
type PageConfig = { eyebrow: string; description: string; columns: Array<[string,string]>; action?: string; endpoint?: string }
const configs: Record<string,PageConfig> = {
  units:{eyebrow:'School structure',description:'Manage physical and online teaching locations.',columns:[['name','Unit'],['code','Code'],['city','City'],['timezone','Timezone'],['active','Status']],action:'Add unit'},
  courses:{eyebrow:'Academic catalog',description:'Build flexible language programs without locking the school to one framework.',columns:[['name','Course'],['code','Code'],['language','Language'],['description','Description'],['active','Status']],action:'Add course'},
  classes:{eyebrow:'Academic operations',description:'Plan cohorts, assign teachers and preserve historical records.',columns:[['name','Class'],['code','Code'],['scheduleDescription','Schedule'],['capacity','Capacity'],['status','Status']],action:'Create class'},
  enrollments:{eyebrow:'Student lifecycle',description:'Connect students to classes and follow their academic result.',columns:[['studentId','Student'],['classId','Class'],['enrolledAt','Enrolled'],['finalResult','Result'],['status','Status']],action:'New enrollment'},
  users:{eyebrow:'Identity and access',description:'Manage user accounts, roles and access without exposing passwords.',columns:[['name','User'],['email','Email'],['roles','Roles'],['lastLoginAt','Last access'],['active','Status']],action:'Add user'},
  administrators:{eyebrow:'Identity and access',description:'Manage privileged school administrators.',columns:[['name','Administrator'],['email','Email'],['roles','Roles'],['lastLoginAt','Last access'],['active','Status']],action:'Add administrator',endpoint:'users?role=administrator'},
  teachers:{eyebrow:'Academic staff',description:'Manage teacher accounts and access.',columns:[['name','Teacher'],['email','Email'],['roles','Roles'],['lastLoginAt','Last access'],['active','Status']],action:'Add teacher',endpoint:'users?role=teacher'},
  students:{eyebrow:'Student administration',description:'Manage student accounts in your authorized scope.',columns:[['name','Student'],['email','Email'],['roles','Roles'],['lastLoginAt','Last access'],['active','Status']],action:'Add student',endpoint:'users?role=student'},
  operators:{eyebrow:'Operations staff',description:'Manage operator accounts and access.',columns:[['name','Operator'],['email','Email'],['roles','Roles'],['lastLoginAt','Last access'],['active','Status']],action:'Add operator',endpoint:'users?role=operator'},
  lessons:{eyebrow:'Learning delivery',description:'Schedule, publish and manage class lessons.',columns:[['title','Lesson'],['scheduledStart','Start'],['scheduledEnd','End'],['teacherId','Teacher'],['status','Status']],action:'Create lesson'},
  exercises:{eyebrow:'Learning activities',description:'Practice with objective, writing, listening and speaking questions.',columns:[['title','Exercise'],['dueAt','Due'],['maxScore','Maximum'],['attemptLimit','Attempts'],['status','Status']],action:'Create exercise'},
  exams:{eyebrow:'Formal assessment',description:'Time-bound assessments with server-owned expiry and secure answers.',columns:[['title','Exam'],['opensAt','Opens'],['closesAt','Closes'],['durationMinutes','Duration'],['status','Status']],action:'Create exam'},
  billing:{eyebrow:'Operational finance',description:'Issue and track charges through the billing provider abstraction.',columns:[['description','Invoice'],['studentId','Student'],['dueDate','Due'],['amountCents','Amount cents'],['status','Status']],action:'Create invoice'},
  support:{eyebrow:'Student service',description:'Handle requester-aware tickets, assignments and internal notes.',columns:[['ticketNumber','Ticket'],['subject','Subject'],['priority','Priority'],['assignedToUserId','Assigned'],['status','Status']],action:'Open ticket'},
  notifications:{eyebrow:'Communication',description:'Review your in-app notifications and realtime delivery.',columns:[['title','Notification'],['type','Type'],['message','Message'],['createdAt','Created'],['readAt','Read']]},
}

export function ConnectedResourcePage({kind,title}:{kind:string;title:string}) {
  const config=configs[kind]
  const location=useLocation()
  const [rows,setRows]=useState<Row[]>([])
  const [loading,setLoading]=useState(Boolean(config))
  const [error,setError]=useState('')
  useEffect(()=>{if(!config)return;const controller=new AbortController();setLoading(true);let endpoint=config.endpoint??kind;if(kind==='students'&&location.pathname.startsWith('/teacher/'))endpoint='teacher/students';const separator=endpoint.includes('?')?'&':'?';fetch(`/api/v1/${endpoint}${separator}limit=50`,{credentials:'include',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('The records could not be loaded.');const body=await response.json() as {items:Row[]};setRows(body.items)}).catch(cause=>{if(cause instanceof Error&&cause.name!=='AbortError')setError(cause.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[kind,config,location.pathname])
  if(!config)return <><PageHeader eyebrow="Workspace" title={title} description="This module follows the shared authorization, loading, empty and error patterns."/><EmptyState title="Module ready for extension" message="Its domain model and navigation are available."/></>
  return <><PageHeader eyebrow={config.eyebrow} title={title} description={config.description} action={config.action?<button className="primary-button"><Plus size={18}/>{config.action}</button>:undefined}/><section className="card resource"><div className="resource-tools"><label><Search/><span className="sr-only">Search</span><input placeholder={`Search ${title}`}/></label><button><Filter/> Filter</button><button><SlidersHorizontal/> Columns</button></div>{loading?<div className="empty" aria-live="polite"><div className="loading-page"><span/><p>Loading records…</p></div></div>:error?<div className="empty" role="alert"><h3>Unable to load {title}</h3><p>{error}</p></div>:rows.length?<div className="table-scroll"><table><thead><tr>{config.columns.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{config.columns.map(([key,label],column)=><td key={label}>{column===0?<b>{display(row[key])}</b>:column===config.columns.length-1?<Badge tone={tone(row[key])}>{display(row[key])}</Badge>:display(row[key])}</td>)}</tr>)}</tbody></table></div>:<EmptyState title={`No ${title.toLowerCase()} yet`} message="Create the first record when your role has permission."/>}<footer className="table-footer"><span>{rows.length} records in the current authorized scope</span></footer></section></>
}
function display(value:unknown):string { if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'active':'inactive';if(typeof value==='number')return String(value);if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleString();return String(value) }
function tone(value:unknown):'success'|'warning'|'danger'|'info'|'neutral' { const status=String(value);if(['active','published','paid','valid', 'true'].includes(status))return 'success';if(['overdue','cancelled','revoked','failed'].includes(status))return 'danger';if(['pending','draft','waiting_user','partial'].includes(status))return 'warning';return 'info' }
