import { Filter, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { Badge, EmptyState, PageHeader } from '../components/ui'
const content: Record<string,{eyebrow:string;title:string;description:string;columns:string[];rows:string[][];action?:string}>={
  units:{eyebrow:'School structure',title:'Units',description:'Manage physical and online teaching locations.',columns:['Unit','Code','Location','Classes','Status'],rows:[['Online Unit','ONLINE','Remote','18','active'],['Downtown Unit','DT-01','São Paulo, SP','12','active'],['North Unit','NT-01','São Paulo, SP','6','active']],action:'Add unit'},
  courses:{eyebrow:'Academic catalog',title:'Courses & levels',description:'Build flexible language programs without locking the school to a single framework.',columns:['Course','Language','Levels','Classes','Status'],rows:[['General English','English','A1–C2','24','active'],['Business English','English','3 levels','8','active'],['Conversation Lab','English','Open level','4','active']],action:'Add course'},
  classes:{eyebrow:'Academic operations',title:'Classes',description:'Plan cohorts, assign teachers and protect historical records.',columns:['Class','Course','Teacher','Schedule','Status'],rows:[['B1 Evening','General English','Sarah Miller','Tue & Thu · 18:30','active'],['Business Pro 2','Business English','Marcus Lee','Mon & Wed · 11:30','active'],['A2 Conversation','Conversation Lab','Ana Costa','Tuesday · 14:00','open']],action:'Create class'},
  enrollments:{eyebrow:'Student lifecycle',title:'Enrollments',description:'Connect students to classes and follow their academic result.',columns:['Student','Class','Enrolled','Progress','Status'],rows:[['Jamie Parker','B1 Evening','Mar 02','72%','active'],['Taylor Reed','B1 Evening','Mar 02','68%','active'],['Noah Kim','Business Pro 2','Apr 14','55%','active']],action:'New enrollment'},
  users:{eyebrow:'Identity & access',title:'Users',description:'Manage accounts, roles and access without exposing passwords.',columns:['User','Email','Role','Last access','Status'],rows:[['Sarah Miller','sarah@example.invalid','Teacher','Today, 08:47','active'],['Jamie Parker','jamie@example.invalid','Student','Yesterday, 19:42','active'],['Morgan Lee','morgan@example.invalid','Operator','Today, 09:02','active']],action:'Add user'},
  billing:{eyebrow:'Operational finance',title:'Billing',description:'Issue and track school charges through a provider abstraction.',columns:['Invoice','Student','Due','Amount','Status'],rows:[['INV-DEMO-1048','Jamie Parker','Aug 12','R$ 489,00','issued'],['INV-DEMO-1047','Taylor Reed','Aug 10','R$ 489,00','overdue'],['INV-DEMO-1046','Noah Kim','Aug 13','R$ 620,00','issued']],action:'Create invoice'},
  support:{eyebrow:'Student service',title:'Support center',description:'Handle requester-aware tickets, assignments and private internal notes.',columns:['Ticket','Subject','Requester','Assigned to','Status'],rows:[['#1042','Cannot access live class','Jamie Parker','Morgan Lee','in progress'],['#1039','Enrollment transfer','Taylor Reed','Unassigned','open'],['#1035','Invoice copy','Noah Kim','Morgan Lee','waiting user']],action:'Open ticket'},
  certificates:{eyebrow:'Certification',title:'Certificates',description:'Issue, revoke and publicly verify privacy-conscious certificates.',columns:['Certificate','Student','Course','Issued','Status'],rows:[['FH-2026-000012','Jamie Parker','General English B1','Aug 10','valid'],['FH-2026-000011','Mia Santos','Conversation Lab','Aug 08','valid'],['FH-2026-000007','Taylor Reed','General English A2','Jul 21','revoked']],action:'Issue certificate'},
  exercises:{eyebrow:'Learning activities',title:'Exercises',description:'Practice with objective, writing, listening and speaking questions.',columns:['Exercise','Class','Due','Submissions','Status'],rows:[['Speaking: Future plans','B1 Evening','Tomorrow','14 / 20','published'],['Airport announcements','B1 Evening','Aug 14','9 / 20','published'],['Writing: City guide','A2 Conversation','Aug 17','3 / 16','draft']],action:'Create exercise'},
  exams:{eyebrow:'Formal assessment',title:'Exams',description:'Time-bound assessments with sections, autosave and backend-enforced expiry.',columns:['Exam','Class','Window','Attempts','Status'],rows:[['B1 Module 2 Checkpoint','B1 Evening','Aug 14 · 18:00','0 / 20','scheduled'],['Business Negotiation','Business Pro 2','Open until Aug 12','11 / 14','open'],['A2 Final Exam','A2 Conversation','Closed','16 / 16','grading']],action:'Create exam'},
  notifications:{eyebrow:'Communication',title:'Notifications',description:'Send in-app updates and monitor scheduled communication events.',columns:['Notification','Audience','Delivery','Created','Status'],rows:[['Class starts in 30 minutes','B1 Evening','In-app SSE','Today, 18:00','scheduled'],['Exercise graded','Jamie Parker','In-app SSE','Today, 09:12','delivered'],['Invoice due','27 students','In-app','Tomorrow','scheduled']],action:'Send notification'},
  audit:{eyebrow:'Accountability',title:'Audit trail',description:'Review important security, academic and operational changes.',columns:['Event','Actor','Resource','Time','Result'],rows:[['grade.revised','Alex Morgan','Exam grade · Jamie Parker','Today, 09:22','recorded'],['ticket.assigned','Morgan Lee','Ticket #1042','Today, 09:10','recorded'],['auth.login_failed','Unknown','User session','Today, 08:51','recorded']]},
  default:{eyebrow:'Workspace',title:'Coming together',description:'This module shares the same authorization, loading, empty and error state patterns.',columns:[],rows:[]}
}
export function ResourcePage({kind,title}:{kind:string;title?:string}){const value=content[kind]??{...content.default,title:title??content.default.title};return <><PageHeader eyebrow={value.eyebrow} title={title??value.title} description={value.description} action={value.action?<button className="primary-button"><Plus size={18}/>{value.action}</button>:undefined}/><section className="card resource"><div className="resource-tools"><label><Search/><span className="sr-only">Search</span><input placeholder={`Search ${title??value.title}`}/></label><button><Filter/> Filter</button><button><SlidersHorizontal/> Columns</button></div>{value.rows.length?<div className="table-scroll"><table><thead><tr>{value.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{value.rows.map((row,index)=><tr key={row[0]}>{row.map((cell,i)=><td key={value.columns[i]}>{i===0?<b>{cell}</b>:i===row.length-1?<Badge tone={['active','valid','published','delivered','recorded'].includes(cell)?'success':['overdue','revoked'].includes(cell)?'danger':'info'}>{cell}</Badge>:cell}</td>)}</tr>)}</tbody></table></div>:<EmptyState title={`No ${title??value.title} yet`} message="Use the primary action to create the first record when you have permission."/>}<footer className="table-footer"><span>Showing {value.rows.length} fictitious demonstration records</span><div><button disabled>Previous</button><button disabled>Next</button></div></footer></section></>}
